Update train.py - calculate
Solving the following error - 

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 3168) + inhomogeneous part.

Modified calculate_metric_with_sklearn method to handle two cases.
1. logits passed to the function are sometimes 3D (tuple)
2. Excluding padding tokens (assuming that its -100).

Let me know if that's not the case and I will surely modify it.